apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - name: web-api-container
          image: your-registry/your-image:your-tag
          ports:
            - containerPort: 443
          env:
            - name: APP_PORT
              value: "8080"
            - name: 
            
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/log.txt
      volumes:
        - name: log-volume
          hostPath:
            path: /path/to/host/log.txt  # Adjust the host path as needed

---
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort  # Use NodePort or LoadBalancer as needed

